name = "url-shortener-api"
main = "api/worker.js"

[[kv_namespaces]]
binding = "URLS"
id = "41eabc24e71543688b87734dea58a297"
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"

[env.production]
[[env.production.kv_namespaces]]
binding = "URLS"
id = "41eabc24e71543688b87734dea58a297"
